services:
  _defaults:
    autowire: true
    autoconfigure: true
  Addictic\ContaoFrontendEditBundle\EventListener\ParseTemplateListener:
    tags:
      - { name: contao.hook, hook: parseTemplate, priority: 0 }
