services:
  _defaults:
    autowire: true
    autoconfigure: true
  Addictic\ContaoFrontendEditBundle\EventListener\ModifyFrontendPageListener:
    tags:
      - { name: contao.hook, hook: modifyFrontendPage, priority: 0 }
  Addictic\ContaoFrontendEditBundle\EventListener\ParseTemplateListener:
    tags:
      - { name: contao.hook, hook: parseTemplate, priority: 0 }
  Addictic\ContaoFrontendEditBundle\Controller\FrontendEditController:
    calls:
      - [setContainer, ['@service_container']]